In [1]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

data = """Artificial intelligence is transforming the future of technology and society.
Machine learning enables systems to improve their performance with experience.
Deep learning is a subset of machine learning that uses multiple layers of neural networks.
Recurrent neural networks are powerful for handling sequential data like text and speech.
Long short term memory networks solve the problem of long range dependencies.
The next word prediction model learns patterns from sequences of words.
Training requires a large dataset of meaningful sentences and phrases.
Text generation is a fascinating application of natural language processing.
Neural networks learn to capture the probability of the next word in context.
Optimization algorithms like Adam and SGD help minimize the training loss.
Large amounts of text data improve the performance of predictive models.
Evaluation metrics such as perplexity measure the quality of predictions.
Language models can be applied to chatbots, translators, and text summarizers.
Modern AI systems rely on deep architectures for state of the art performance.
Data preprocessing is an important step in building robust models.
Cleaning and tokenizing text ensures better learning during training.
Vocabulary size determines the range of words that the model can predict.
Embedding layers convert words into vector representations for the network.
The sequence length defines how many previous words are used for prediction.
Model training requires careful tuning of hyperparameters for accuracy.
A validation dataset is used to monitor overfitting during training.
Regularization techniques like dropout prevent the model from memorizing data.
Batch size affects the stability and speed of gradient descent.
Learning rate controls how quickly the model updates its weights.
Too high a learning rate may cause the model to diverge during training.
Too low a learning rate may slow down convergence of the model.
Loss functions like categorical crossentropy are used for word prediction.
The softmax function outputs the probability distribution for the next word.
Predicted probabilities indicate the likelihood of different possible words.
Beam search can be used for more accurate text generation.
Greedy search simply chooses the most probable next word at each step.
Sampling techniques introduce randomness into generated text.
Language models capture both grammar and semantic meaning.
Context plays a crucial role in predicting the correct next word.
The quality of predictions improves with more diverse training data.
Training can be done using GPUs to speed up computations.
Evaluation helps determine if the model is generalizing well.
Transfer learning allows the use of pre trained embeddings like GloVe or Word2Vec.
Fine tuning can adapt pre trained models to specific datasets.
Large models require more computation and memory to train effectively.
Data augmentation strategies can enrich the training dataset.
Generated text should be coherent and contextually relevant.
Applications of next word prediction include mobile keyboards and assistants.
Predictive typing saves time by suggesting the next word to users.
Context aware models improve user experience in real world applications.
Next word prediction is a step toward full sentence generation.
Sequence to sequence models can handle tasks like translation and summarization.
Attention mechanisms enhance the ability of models to focus on important words.
Transformer models achieve remarkable results in natural language tasks.
BERT and GPT are examples of powerful transformer architectures.
These models are trained on billions of words from large corpora.
Pre trained models can be fine tuned for specific downstream tasks.
Natural language understanding is key to conversational AI systems.
Speech recognition systems also benefit from language models.
Autocomplete features rely heavily on next word prediction models.
AI powered search engines use language models for query understanding.
Personal assistants like Siri and Alexa use predictive language technologies.
Chatbots employ language models to generate human like responses.
Educational tools use AI to provide personalized learning experiences.
Healthcare applications of AI include analyzing patient records and notes.
Financial institutions use predictive models for fraud detection and analysis.
Business intelligence systems rely on machine learning for decision making.
Social media platforms use language models for content moderation.
Recommendation systems use AI to suggest items based on user behavior.
The ethics of AI requires careful consideration of fairness and bias.
Responsible AI development ensures models do not harm individuals.
Bias in training data can lead to unfair or inaccurate predictions.
Transparency in AI helps build trust between humans and machines.
Explainable AI is a growing field of research in machine learning.
The interpretability of models allows humans to understand decisions.
Open source libraries make AI development accessible to everyone.
Frameworks like TensorFlow and PyTorch are widely used for deep learning.
Keras provides a high level API for building neural networks quickly.
Model deployment involves serving trained models to real users.
APIs enable integration of AI models into applications and services.
Scalability is important when serving models to millions of users.
Cloud platforms provide infrastructure for training and deploying AI models.
Edge devices allow AI models to run locally without internet.
Model compression techniques reduce the size of large neural networks.
Quantization and pruning are common strategies for efficient models.
Energy efficient AI is an emerging research area for sustainability.
Future AI systems may combine reasoning with statistical learning.
Human and AI collaboration can enhance creativity and productivity.
Education about AI is essential for preparing the future workforce.
Ethical guidelines are necessary for safe and fair AI usage.
The future of AI depends on responsible innovation and governance.
"""

tokenizer = Tokenizer()

tokenizer.fit_on_texts([data])

In [2]:
tokenizer.index_word

{1: 'the',
 2: 'of',
 3: 'and',
 4: 'models',
 5: 'to',
 6: 'for',
 7: 'ai',
 8: 'learning',
 9: 'is',
 10: 'training',
 11: 'a',
 12: 'word',
 13: 'model',
 14: 'language',
 15: 'can',
 16: 'like',
 17: 'next',
 18: 'are',
 19: 'text',
 20: 'in',
 21: 'systems',
 22: 'data',
 23: 'words',
 24: 'on',
 25: 'use',
 26: 'networks',
 27: 'prediction',
 28: 'neural',
 29: 'large',
 30: 'be',
 31: 'used',
 32: 'trained',
 33: 'future',
 34: 'machine',
 35: 'from',
 36: 'predictive',
 37: 'applications',
 38: 'improve',
 39: 'performance',
 40: 'with',
 41: 'deep',
 42: 'requires',
 43: 'dataset',
 44: 'generation',
 45: 'natural',
 46: 'context',
 47: 'predictions',
 48: 'rely',
 49: 'important',
 50: 'step',
 51: 'during',
 52: 'size',
 53: 'into',
 54: 'sequence',
 55: 'techniques',
 56: 'rate',
 57: 'may',
 58: 'search',
 59: 'more',
 60: 'pre',
 61: 'users',
 62: 'tasks',
 63: 'intelligence',
 64: 'experience',
 65: 'that',
 66: 'layers',
 67: 'powerful',
 68: 'speech',
 69: 'long',
 70:

In [3]:
input_sequannce=[]
for sentence in data.split('\n'):
  tokanized_sentence=tokenizer.texts_to_sequences([sentence])[0]
  for i in range(1, len(tokanized_sentence)):
    input_sequannce.append(tokanized_sentence[:i+1])




In [4]:
input_sequannce

[[113, 63],
 [113, 63, 9],
 [113, 63, 9, 114],
 [113, 63, 9, 114, 1],
 [113, 63, 9, 114, 1, 33],
 [113, 63, 9, 114, 1, 33, 2],
 [113, 63, 9, 114, 1, 33, 2, 115],
 [113, 63, 9, 114, 1, 33, 2, 115, 3],
 [113, 63, 9, 114, 1, 33, 2, 115, 3, 116],
 [34, 8],
 [34, 8, 117],
 [34, 8, 117, 21],
 [34, 8, 117, 21, 5],
 [34, 8, 117, 21, 5, 38],
 [34, 8, 117, 21, 5, 38, 118],
 [34, 8, 117, 21, 5, 38, 118, 39],
 [34, 8, 117, 21, 5, 38, 118, 39, 40],
 [34, 8, 117, 21, 5, 38, 118, 39, 40, 64],
 [41, 8],
 [41, 8, 9],
 [41, 8, 9, 11],
 [41, 8, 9, 11, 119],
 [41, 8, 9, 11, 119, 2],
 [41, 8, 9, 11, 119, 2, 34],
 [41, 8, 9, 11, 119, 2, 34, 8],
 [41, 8, 9, 11, 119, 2, 34, 8, 65],
 [41, 8, 9, 11, 119, 2, 34, 8, 65, 120],
 [41, 8, 9, 11, 119, 2, 34, 8, 65, 120, 121],
 [41, 8, 9, 11, 119, 2, 34, 8, 65, 120, 121, 66],
 [41, 8, 9, 11, 119, 2, 34, 8, 65, 120, 121, 66, 2],
 [41, 8, 9, 11, 119, 2, 34, 8, 65, 120, 121, 66, 2, 28],
 [41, 8, 9, 11, 119, 2, 34, 8, 65, 120, 121, 66, 2, 28, 26],
 [122, 28],
 [122, 28, 26

In [5]:
max_len=max([len(x) for x in  input_sequannce])

In [6]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequance=pad_sequences(input_sequannce,maxlen = max_len,padding='pre')

In [7]:
padded_input_sequance

array([[  0,   0,   0, ...,   0, 113,  63],
       [  0,   0,   0, ..., 113,  63,   9],
       [  0,   0,   0, ...,  63,   9, 114],
       ...,
       [  0,   0,   0, ...,  24, 107, 415],
       [  0,   0,   0, ..., 107, 415,   3],
       [  0,   0,   0, ..., 415,   3, 416]], dtype=int32)

In [8]:
x=padded_input_sequance[:,:-1]

In [9]:
y=padded_input_sequance[:,-1]

In [10]:
print(x)

[[  0   0   0 ...   0   0 113]
 [  0   0   0 ...   0 113  63]
 [  0   0   0 ... 113  63   9]
 ...
 [  0   0   0 ... 414  24 107]
 [  0   0   0 ...  24 107 415]
 [  0   0   0 ... 107 415   3]]


In [11]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y, num_classes=len(tokenizer.word_index) + 1)

In [12]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [13]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

In [14]:
model=Sequential()
model.add(Embedding(417,100,input_length=56))
model.add(LSTM(150))
model.add(Dense(417,activation='softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [15]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [16]:
model.build(input_shape=(None, 56))
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 56, 100)        │        41,700 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 150)            │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 417)            │        62,967 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 255,267 (997.14 KB)

 Trainable params: 255,267 (997.14 KB)

 Non-trainable params: 0 (0.00 B)

In [17]:
x

array([[  0,   0,   0, ...,   0,   0, 113],
       [  0,   0,   0, ...,   0, 113,  63],
       [  0,   0,   0, ..., 113,  63,   9],
       ...,
       [  0,   0,   0, ..., 414,  24, 107],
       [  0,   0,   0, ...,  24, 107, 415],
       [  0,   0,   0, ..., 107, 415,   3]], dtype=int32)

In [18]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [19]:
model.fit(x,y,epochs=100)

Epoch 1/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.0129 - loss: 5.9946
Epoch 2/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0492 - loss: 5.5213
Epoch 3/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0438 - loss: 5.3339
Epoch 4/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0437 - loss: 5.3633
Epoch 5/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0348 - loss: 5.2349
Epoch 6/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0526 - loss: 5.1209
Epoch 7/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0536 - loss: 5.0232
Epoch 8/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0661 - loss: 4.9028
Epoch 9/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0560 - loss: 4.9424
Epoch 10/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0676 - loss: 4.8360
Epoch 11/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0815 - loss: 4.6306
Epoch 12/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy:

In [20]:
import numpy as np

In [22]:
import time
for i in range(5):
 text = "learning"
 tokentext = tokenizer.texts_to_sequences([text])[0]
 padded_token_text = pad_sequences([tokentext], maxlen=max_len, padding='pre')
 pos = np.argmax(model.predict(padded_token_text))
 time.sleep(2)
 for word , index in tokenizer.word_index.items():
    if index == pos:
      text=text + "the" + word
      print(word)





1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
rate
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
rate
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
rate
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
rate
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
rate
